Repository chsami/microbot, pull requests merged in 2023-09, with the labels that each got.

#23 [NEW PLUGIN] Auto ZMI Altar
  runelite-client/src/main/java/net/runelite/client/plugins/jrPlugins/autoZMIAltar/AutoZMIAltar.kt
  runelite-client/src/main/java/net/runelite/client/plugins/jrPlugins/autoZMIAltar/AutoZMIAltarConfig.java
  runelite-client/src/main/java/net/runelite/client/plugins/jrPlugins/autoZMIAltar/AutoZMIAltarOverlay.java
  runelite-client/src/main/java/net/runelite/client/plugins/jrPlugins/autoZMIAltar/BANK.kt
  runelite-client/src/main/java/net/runelite/client/plugins/jrPlugins/autoZMIAltar/STAMINA.kt
  runelite-client/src/main/java/net/runelite/client/plugins/jrPlugins/autoZMIAltar/TELEPORT.kt
  runelite-client/src/main/java/net/runelite/client/plugins/skillcalculator/skills/MagicAction.java
Labels: enhancement

#27 [PLUGIN UPDATE] Auto ZMI Faster Banking & NPC Contact
  runelite-client/src/main/java/net/runelite/client/plugins/jrPlugins/autoChin/AutoChin.kt
  runelite-client/src/main/java/net/runelite/client/plugins/jrPlugins/autoVorkath/AutoVorkathPlugin.kt
  runelite-client/src/main/java/net/runelite/client/plugins/jrPlugins/autoZMIAltar/AutoZMIAltar.kt
Labels: Plugin Update

#36 [BUG FIX] Rs2GameObject Imposter IDs
  runelite-client/src/main/java/net/runelite/client/plugins/jrPlugins/autoZMIAltar/AutoZMIAltar.kt
  runelite-client/src/main/java/net/runelite/client/plugins/jrPlugins/autoZMIAltar/AutoZMIAltarConfig.java
  runelite-client/src/main/java/net/runelite/client/plugins/microbot/util/gameobject/Rs2GameObject.java
Labels: bug

#73 add ability to define how far to stray from starting position
  runelite-client/src/main/java/net/runelite/client/plugins/microbot/woodcutting/WoodcuttingConfig.java
  runelite-client/src/main/java/net/runelite/client/plugins/microbot/woodcutting/WoodcuttingScript.java
Labels: enhancement
